project:
  type: website
  output-dir: docs
# for comments
website:
  title: "josenino95.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects & Publications
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

